-- =============================================================================
-- ATLAS Capital Delivery - SPCS Access Grants
-- =============================================================================
-- Run this script to grant access to the ATLAS service
-- =============================================================================

USE DATABASE CAPITAL_PROJECTS_DB;
USE SCHEMA SPCS;

-- Grant usage on compute pool
GRANT USAGE ON COMPUTE POOL ATLAS_COMPUTE_POOL TO ROLE ATLAS_APP_ROLE;

-- Grant usage on image repository
GRANT READ ON IMAGE REPOSITORY ATLAS_IMAGES TO ROLE ATLAS_APP_ROLE;

-- Grant service access
GRANT USAGE ON SERVICE ATLAS_SERVICE TO ROLE ATLAS_APP_ROLE;

-- Grant access to database and schemas
GRANT USAGE ON DATABASE CAPITAL_PROJECTS_DB TO ROLE ATLAS_APP_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE CAPITAL_PROJECTS_DB TO ROLE ATLAS_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CAPITAL_PROJECTS_DB.ATOMIC TO ROLE ATLAS_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA CAPITAL_PROJECTS_DB.ML TO ROLE ATLAS_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA CAPITAL_PROJECTS_DB.CAPITAL_PROJECTS TO ROLE ATLAS_APP_ROLE;

-- Grant access to Cortex Search services
GRANT USAGE ON CORTEX SEARCH SERVICE CAPITAL_PROJECTS_DB.DOCS.CO_SEARCH_SERVICE TO ROLE ATLAS_APP_ROLE;
GRANT USAGE ON CORTEX SEARCH SERVICE CAPITAL_PROJECTS_DB.DOCS.CONTRACT_SEARCH_SERVICE TO ROLE ATLAS_APP_ROLE;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE CAPITAL_COMPUTE_WH TO ROLE ATLAS_APP_ROLE;
GRANT USAGE ON WAREHOUSE CAPITAL_ML_WH TO ROLE ATLAS_APP_ROLE;

-- Output
SELECT 'Access grants complete for ATLAS_APP_ROLE' as STATUS;
